# Generated by Django 6.1.1 on 2026-09-04 18:55

import django.core.validators
import django.db.models.deletion
import social_api.models.app.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "certifications",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "industries",
                "db_table": "industries",
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "interests",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="ISO 639-1", max_length=2, null=True
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="OccupationLevel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "occupation_levels",
            },
        ),
        migrations.CreateModel(
            name="OccupationRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "occupation_roles",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "password",
                    models.CharField(db_column="password_hash", max_length=128),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", social_api.models.app.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(help_text="e.g. people-data-labs", max_length=255),
                ),
                ("filename", models.CharField(max_length=255)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "import batches",
                "db_table": "import_batches",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("City", "City"),
                            ("Region", "Region"),
                            ("Country", "Country"),
                        ],
                        max_length=15,
                    ),
                ),
                ("locality", models.CharField(blank=True, max_length=126, null=True)),
                ("metro", models.CharField(blank=True, max_length=126, null=True)),
                ("region", models.CharField(blank=True, max_length=126, null=True)),
                ("country", models.CharField(blank=True, max_length=126, null=True)),
                ("continent", models.CharField(blank=True, max_length=126, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "region", "locality"),
                        name="locations_country_region_locality_uniq",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="job_company_id from source",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="bucket, e.g. 1001-5000",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("founded_year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="social_api.industry",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="social_api.location",
                    ),
                ),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupations",
                        to="social_api.industry",
                    ),
                ),
            ],
            options={
                "db_table": "occupations",
            },
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(help_text="raw title as sourced", max_length=255),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employments",
                        to="social_api.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employments",
                        to="social_api.location",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employments",
                        to="social_api.occupation",
                    ),
                ),
                (
                    "occupation_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employments",
                        to="social_api.occupationrole",
                    ),
                ),
            ],
            options={
                "db_table": "employments",
            },
        ),
        migrations.CreateModel(
            name="EmploymentLevel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "employment_id",
                        "occupation_level_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_links",
                        to="social_api.employment",
                    ),
                ),
                (
                    "occupation_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_links",
                        to="social_api.occupationlevel",
                    ),
                ),
            ],
            options={
                "db_table": "employment_levels",
            },
        ),
        migrations.CreateModel(
            name="OccupationSubRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occupation_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_roles",
                        to="social_api.occupationrole",
                    ),
                ),
            ],
            options={
                "db_table": "occupation_sub_roles",
            },
        ),
        migrations.AddField(
            model_name="employment",
            name="occupation_sub_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employments",
                to="social_api.occupationsubrole",
            ),
        ),
        migrations.CreateModel(
            name="Personality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=512)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "inferred_salary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "inferred_years_experience",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("version_status", models.JSONField(blank=True, null=True)),
                ("location_last_updated", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personalities",
                        to="social_api.importbatch",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personalities",
                        to="social_api.industry",
                    ),
                ),
            ],
            options={
                "db_table": "personalities",
            },
        ),
        migrations.AddField(
            model_name="employment",
            name="personality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to="social_api.personality",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                help_text="optional self-link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="social_api.personality",
            ),
        ),
        migrations.CreateModel(
            name="PersonalityCertification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.certification",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_links",
                        to="social_api.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_certifications",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="certifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalityCertification",
                to="social_api.certification",
            ),
        ),
        migrations.CreateModel(
            name="PersonalityInterest",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "personality_id",
                        "interest_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.interest",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_links",
                        to="social_api.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_interests",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalityInterest",
                to="social_api.interest",
            ),
        ),
        migrations.CreateModel(
            name="PersonalityLanguage",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "personality_id",
                        "language_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="0-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.language",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_links",
                        to="social_api.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_languages",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalityLanguage",
                to="social_api.language",
            ),
        ),
        migrations.CreateModel(
            name="PersonalityLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.location",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="social_api.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_locations",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalityLocation",
                to="social_api.location",
            ),
        ),
        migrations.CreateModel(
            name="PersonalitySkill",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "personality_id",
                        "skill_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_links",
                        to="social_api.personality",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.skill",
                    ),
                ),
            ],
            options={
                "db_table": "personality_skills",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalitySkill",
                to="social_api.skill",
            ),
        ),
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "social_platforms",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug",), name="unique_social_platform_slug"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanySocialProfiles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_api.company",
                    ),
                ),
                (
                    "social_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_api.socialplatform",
                    ),
                ),
            ],
            options={
                "db_table": "company_social_profiles",
            },
        ),
        migrations.CreateModel(
            name="SocialProfiles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("connection_count", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_api.personality",
                    ),
                ),
                (
                    "social_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_api.socialplatform",
                    ),
                ),
            ],
            options={
                "db_table": "social_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="companies_name_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["website"], name="companies_website_idx"),
        ),
        migrations.AddConstraint(
            model_name="occupationsubrole",
            constraint=models.UniqueConstraint(
                fields=("occupation_role", "slug"),
                name="occupation_sub_roles_role_slug_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="employment",
            index=models.Index(
                fields=["personality", "is_current"], name="employments_person_curr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employment",
            index=models.Index(fields=["company"], name="employments_company_idx"),
        ),
        migrations.AddConstraint(
            model_name="employment",
            constraint=models.UniqueConstraint(
                fields=("personality", "company", "title", "start_date"),
                name="employments_person_co_title_start_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="personalitycertification",
            constraint=models.UniqueConstraint(
                fields=("personality", "certification", "start_date"),
                name="personality_certifications_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="personalitylanguage",
            constraint=models.CheckConstraint(
                condition=models.Q(("proficiency__gte", 0), ("proficiency__lte", 5)),
                name="personality_languages_proficiency_range",
            ),
        ),
        migrations.AddIndex(
            model_name="personalitylocation",
            index=models.Index(
                fields=["personality", "location", "street_address"],
                name="personality_location_addr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalitylocation",
            index=models.Index(
                fields=["personality", "location"], name="personality_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["full_name"], name="personalities_full_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["last_name", "first_name"], name="personalities_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companysocialprofiles",
            constraint=models.UniqueConstraint(
                fields=("social_platform", "company"),
                name="unique_company_social_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialprofiles",
            constraint=models.UniqueConstraint(
                fields=("social_platform", "user_name"), name="unique_social_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialprofiles",
            constraint=models.UniqueConstraint(
                fields=("social_platform", "platform_user_id"),
                name="unique_social_platform",
            ),
        ),
    ]
