# Generated by Django 6.1.1 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("import_batch_id", models.IntegerField(blank=True, null=True)),
                ("industry_id", models.IntegerField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=512)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "inferred_salary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "inferred_years_experience",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("version_status", models.JSONField(blank=True, null=True)),
                ("location_last_updated", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "personalities",
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="personalities_full_name_idx"
                    ),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="personalities_name_idx",
                    ),
                    models.Index(
                        fields=["industry_id"], name="personalities_industry_idx"
                    ),
                ],
            },
        ),
    ]
