# Generated by Django 6.1.1 on 2026-09-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("City", "City"),
                            ("Region", "Region"),
                            ("Country", "Country"),
                        ],
                        max_length=15,
                    ),
                ),
                ("locality", models.CharField(blank=True, max_length=126, null=True)),
                ("metro", models.CharField(blank=True, max_length=126, null=True)),
                ("region", models.CharField(blank=True, max_length=126, null=True)),
                ("country", models.CharField(blank=True, max_length=126, null=True)),
                ("continent", models.CharField(blank=True, max_length=126, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "region", "locality"),
                        name="locations_country_region_locality_uniq",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonalityLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_links",
                        to="social_api.location",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="social_api.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_locations",
            },
        ),
        migrations.AddField(
            model_name="personality",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="personalities",
                through="social_api.PersonalityLocation",
                to="social_api.location",
            ),
        ),
        migrations.AddIndex(
            model_name="personalitylocation",
            index=models.Index(
                fields=["personality", "location", "street_address"],
                name="personality_location_addr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalitylocation",
            index=models.Index(
                fields=["personality", "location"], name="personality_location_idx"
            ),
        ),
    ]
