# Generated by Django 6.1.1 on 2026-09-05 09:30

import django.db.models.deletion
import social_api.models.app.import_batch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportChunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("index", models.PositiveIntegerField()),
                ("start_offset", models.BigIntegerField()),
                ("end_offset", models.BigIntegerField()),
                ("first_row", models.PositiveIntegerField(default=1)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_rows", models.IntegerField(default=0)),
                ("created_rows", models.IntegerField(default=0)),
                ("updated_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "import_chunks",
                "ordering": ("batch", "index"),
            },
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="1-based data row within the source file."
                    ),
                ),
                ("message", models.TextField()),
                ("excerpt", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "import_row_errors",
                "ordering": ("batch", "row_number"),
            },
        ),
        migrations.AlterModelOptions(
            name="importbatch",
            options={
                "ordering": ("-created_at",),
                "verbose_name_plural": "import batches",
            },
        ),
        migrations.AddField(
            model_name="importbatch",
            name="created_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="failed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Deleted once the batch reaches a terminal state.",
                max_length=500,
                null=True,
                upload_to=social_api.models.app.import_batch.import_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="header_end",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="pending_chunks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="processed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("planning", "Planning"),
                    ("processing", "Processing"),
                    ("finalising", "Finalising"),
                    ("completed", "Completed"),
                    ("partial", "Completed with errors"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="total_chunks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="updated_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personality",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="linkedin_id from the source, falling back to linkedin_username.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="row_count",
            field=models.IntegerField(
                blank=True, help_text="Data rows found while planning.", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="personalitylocation",
            constraint=models.UniqueConstraint(
                fields=("personality", "location", "street_address"),
                name="personality_locations_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddField(
            model_name="importchunk",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="social_api.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importrowerror",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_errors",
                to="social_api.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importrowerror",
            name="chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="row_errors",
                to="social_api.importchunk",
            ),
        ),
        migrations.AddConstraint(
            model_name="importchunk",
            constraint=models.UniqueConstraint(
                fields=("batch", "index"), name="import_chunks_batch_index_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="importrowerror",
            index=models.Index(
                fields=["batch", "row_number"], name="import_row_errors_idx"
            ),
        ),
    ]
